### ISSUE TITLE
Page with identifier with position incorrectly considered invalid

### ISSUE THREAD

**Issue by webignition** [webignition/basil-data-validator#51]
```yaml
url: "http://example.com"
elements:
  form: $".form":3
  inputs: $"{{ form }} .inputs"
  name_input: $"{{ inputs }} .name"
  email_input: $"{{ inputs }} .email"
  submit_button: $"{{ form }} .submit"
```

The identifier `$".form":3` is unambiguous and should be allowed to go ahead.
